Делает майн, футер и добавляет катртинки
htmlacademy-htmlcss/1577735-sedona-33 pull request #2
Opened 2022-01-22 15:21 UTC by Alekzander87

2022-01-24 18:29 UTC, baileys-li requested changes

2022-01-24 18:29 UTC, baileys-li commented on Readme.md
> +>>>>>>> 843794401de56edf3d366c7dbfe45a0a8678722c
Ты где уже умудрился конфликт получить?!!

2022-01-24 18:29 UTC, baileys-li commented on index.html
> +                  d="M97.8768 3.58164V1.19388H99.9827L97.8768 3.58164ZM48.5371 12.9337C48.6374 13.0332 50.9439 10.5459 54.6544 8.0587C58.0641 5.77043 63.2788 3.18368 69.0953 3.18368C74.9118 3.18368 8
Логотип всё-таки не должен быть частью списка с остальной навигации. Слишком разные элементы

2022-01-24 18:29 UTC, baileys-li commented on index.html
> +          <input type="email" name="email" placeholder="Ваш e-mail">
Нет подписи. См сообщение в телеге

2022-01-24 18:53 UTC, baileys-li commented on index.html
> +            <img src="images/photo-1.jpg" alt="Улица города">
Хаос со списком. Смотри сообщение телеги

2022-01-24 19:09 UTC, baileys-li commented on index.html
> +          <img src="" alt="Описание картинки">
```suggestion
          <img src="" alt="HTML Academy">
```

2022-01-24 19:09 UTC, baileys-li commented on index.html
> +      <h1 class="vissually-hidden">Зона отдыха "Седона"</h1>
Сюда рядом лучше вставить ещё картинку с текстом из макета. См телегу

2022-01-24 20:38 UTC, baileys-li commented on catalog.html
> +                </ul>
Хлебные крошки лучше делать нумерованным списком

2022-01-24 20:39 UTC, baileys-li commented on catalog.html
> +                        <a class="favorites" href="#">В избранное</a>
В избранное больше кнопка подходит

2022-01-24 20:40 UTC, baileys-li commented on catalog.html
> +                        <img class="star" src="" alt="Описание картинки">
Пока пиши просто
```suggestion
                        <span>4 звезды</span>
```

И прочее. Я потом сделаю демку с разными вариантами

2022-01-24 21:03 UTC, baileys-li commented on catalog.html
> +                    </li>
Лучше сделать ненумерованным списком. Где в каждом `a` будет номер страницы.

А многоточие будет кнопкой

2022-01-26 16:19 UTC, Alekzander87 commented on index.html
> +          <input type="email" name="email" placeholder="Ваш e-mail">
Сделал так, чтобы при клике на заголовок можно было вводить почту. Оставить или сделать как ты показал в начале видео?

2022-01-26 16:22 UTC, Alekzander87 commented on index.html
> +      <h1 class="vissually-hidden">Зона отдыха "Седона"</h1>
В макете картинки часть первой секции, я их туда вставил. Или их всё же поставить перед первой секцией?

2022-01-26 16:23 UTC, Alekzander87 commented on catalog.html
> +                        <img class="star" src="" alt="Описание картинки">
спану класс задавать?

2022-01-26 16:27 UTC, Alekzander87 commented on catalog.html
> +                    </li>
многоточие часть списка?

2022-01-26 16:55 UTC, Alekzander87 commented on Readme.md
> +>>>>>>> 843794401de56edf3d366c7dbfe45a0a8678722c
видимо не стоило с телефона куда попало тыкать))
вроде исправил)

2022-01-26 18:26 UTC, baileys-li commented on index.html
> +          <input type="email" name="email" placeholder="Ваш e-mail">
@Alekzander87 любой вариант подходит. Главное, чтобы была подпись

2022-01-26 18:27 UTC, baileys-li commented on index.html
> +      <h1 class="vissually-hidden">Зона отдыха "Седона"</h1>
Я бы выделил в отдельный блок. Но тут уже на усмотрение конкретного разработчика

2022-01-26 18:28 UTC, baileys-li commented on catalog.html
> +                        <img class="star" src="" alt="Описание картинки">
@Alekzander87 да, можно. Сейчас все равно стилизации нет, поэтому непринципиально

2022-01-26 18:28 UTC, baileys-li commented on catalog.html
> +                    </li>
Да, поэтому не подходит нумерованный. Многоточие под номер не очень подходит

2022-01-26 19:44 UTC, Alekzander87 commented
вносит правки от наставника

2022-01-26 21:36 UTC, baileys-li commented on catalog.html
> +                        <input class="range-slider-input" type="range" min="0" max="12000" value="0" step="100" aria-label="minrange">
`aria-label` будет читаться скринридером, он должен быть понятным
```suggestion
                        <input class="range-slider-input" type="range" min="0" max="12000" value="0" step="100" aria-label="Ползунок минимальной цены">
```

2022-01-26 21:37 UTC, merged